# Default values for nest-boilerplate-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
######### backend env #############
  backend:
    image: backend:latest
    pullPolicy: IfNotPresent
    enabled: true
    replicaCount: 2
    containerPort: 80
    defaultMode: 420
    ingressPort: 3000
    serviceExternalPort: 3000
    serviceInternalPort: 8888
    serviceType: ClusterIP
    serviceName: backend-service
    ingressName: backend-ingress
    env:
      NODE_ENV: local
      PORT: 8888
      APP_PORT: 8888
      API_PREFIX: /v1
      # redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispass
      # database
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_HOST: nest-boilerplate-helm-postgres # use this when use k8s
      DATABASE_PORT: 5432 # Internal port for container to container communication
      DATABASE_NAME: test_db
      DATABASE_URL: postgresql://test:test@localhost:5432/test_db?schema=public
      DB_TIMEZONE: UTC
      # JWT
      JWT_SECRET_KEY: binhle
      ACCESS_TOKEN_EXPIRE_TIME: 3600s
      REFRESH_TOKEN_EXPIRE_TIME: 86400s
      # cookie
      COOKIE_SECRET_KEY: binhle@123-COOKIE
      ACCESS_COOKIE_EXPIRE_TIME: 900000
      REFRESH_COOKIE_EXPIRE_TIME: 604800000
      # session
      SESSION_SECRET_KEY: binhle@123-SESSION
      # csrf
      CSRF_TOKEN_HEADER: __Host-blank.X-CSRF-Token
      # mail
      MAIL_HOST: smtp.gmail.com
      MAIL_USER: xxxxxxx
      MAIL_PASSWORD: xxxxxxx
      MAIL_FROM: noreply@example.com
      MAIL_TRANSPORT: xxxxxxx
      FE_URL: ''
      FACEBOOK_APP_ID: xxxxxxx
      FACEBOOK_APP_SECRET: xxxxxxx
      FACEBOOK_APP_REDIRECT_URL: xxxxxxx
      GOOGLE_APP_ID: xxxxxxx
      GOOGLE_APP_SECRET: xxxxxxx
      GOOGLE_APP_REDIRECT_URL: xxxxxxx
      # helm config
      PORT_HELM: 3000
      TARGET_PORT_HELM: 8888
######### postgres env #############
  postgres:
    image: postgres:16.2-alpine
    pullPolicy: IfNotPresent
    enabled: true
    replicaCount: 1
    serviceExternalPort: 5432
    serviceInternalPort: 5432
    containerPort: 5432
    serviceType: ClusterIP
    serviceName: backend-service
    env:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      TZ: UTC
