apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-postgres
  labels:
    app: {{ .Chart.Name }}-postgres
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
      - name: {{ .Chart.Name }}-postgres
        image: {{ .Values.postgres.image }}
        env:
        {{- range $key, $value := .Values.postgres.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
