apiVersion: skaffold/v4beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.DIGEST}}"
  artifacts:
    - image: backend-skaffold-helm
      context: .
      docker:
        dockerfile: docker/Dockerfile

deploy:
  helm:
    releases:
      - name: backend
        chartPath: charts/backend
        setValues:
          image: backend-skaffold-helm
        valuesFiles:
          - charts/backend/values.yaml
      - name: postgres
        chartPath: charts/postgres
        setValues:
          postgres.image: postgres:16.2-alpine
        valuesFiles:
          - charts/postgres/values.yaml
