apiVersion: skaffold/v1
kind: Config
metadata:
  name: dev-nestjs-kubernetes
build:
  artifacts:
    - image: lebinh89/nest_boilerplate
      context: .
      docker:
        dockerfile: ./docker/Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.*'
            dest: .
deploy:
  kubectl:
    flags:
      global: [--namespace=nestjs-kubernetes-namespace]
    manifests:
      - ./kubernetes/03-secrets.yaml
      - ./kubernetes/04-postgres.yaml
      - ./kubernetes/05-redis.yaml
      - ./kubernetes/06-data.yaml
      - ./kubernetes/07-nestjs.yaml
