apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceConfig.serviceName }}
  labels:
    {{- include "nest-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceConfig.type }}
  ports:
    - port: {{ .Values.serviceConfig.serviceExternalPort }}
      targetPort: {{ .Values.serviceConfig.serviceInternalPort }}
      protocol: TCP
      name: {{ .Values.serviceConfig.serviceName }}
  selector:
    {{- include "nest-backend.selectorLabels" . | nindent 4 }}
