apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
        - image: lebinh89/nest_boilerplate:latest
          name: leon-app-example-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: 'leon-redis'
            - name: REDIS_PORT
              value: '6379'
            - name: DB_HOST
              value: 'leon-postgres'
            - name: DB_PORT
              value: '5432'
            - name: DB_USERNAME
              value: 'test'
            - name: DB_PASSWORD
              value: 'test'
            - name: DB_NAME
              value: 'test_db'
            - name: DB_TIMEZONE
              value: 'UTC'
