apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-config
data:
  DATABASE_USERNAME: 'test'
  DATABASE_PASSWORD: 'test'
  DATABASE_PORT: '5432'
  DATABASE_HOST: 'postgres-service'
  DATABASE_NAME: 'test_db'
  DB_TIMEZONE: 'UTC'
  REDIS_HOST: 'redis'
  REDIS_PORT: '6379'
  REDIS_PASSWORD: 'redispass'
  PORT: '8888'
  APP_PORT: '8888'
  API_PREFIX: '/v1'
  NODE_ENV: 'local'
  JWT_SECRET_KEY: 'binhle'
  ACCESS_TOKEN_EXPIRE_TIME: '3600s'
  REFRESH_TOKEN_EXPIRE_TIME: '86400s'
  COOKIE_SECRET_KEY: 'binhle@123-COOKIE'
  ACCESS_COOKIE_EXPIRE_TIME: '900000'
  REFRESH_COOKIE_EXPIRE_TIME: '604800000'
  SESSION_SECRET_KEY: 'binhle@123-SESSION'
  CSRF_TOKEN_HEADER: '__Host-blank.X-CSRF-Token'
  MAIL_HOST: 'smtp.gmail.com'
  MAIL_USER: 'binhloc25012015@gmail.com'
  MAIL_PASSWORD: 'zhbmujfharyqmoae'
  MAIL_FROM: 'noreply@example.com'
  MAIL_TRANSPORT: 'smtp://${MAIL_USER}:${MAIL_PASSWORD}@${MAIL_HOST}'
  FACEBOOK_APP_ID: '257726123435704'
  FACEBOOK_APP_SECRET: '9f863db197c09460a8be60aa2fb70c3a'
  FACEBOOK_APP_REDIRECT_URL: 'http://localhost:8888/v1/auth/facebook/redirect'
  GOOGLE_APP_ID: '732252870480-tgovfhjd8ig812b1b7bsevgaptnmi0rc.apps.googleusercontent.com'
  GOOGLE_APP_SECRET: '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'
  GOOGLE_APP_REDIRECT_URL: 'http://localhost:8888/v1/auth/google/redirect'
