apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: PG_DATA
              value: /var/lib/postgresql/pgdata
            - name: POSTGRES_DB
              value: test_db
            - name: POSTGRES_PASSWORD
              value: test
            - name: POSTGRES_USER
              value: test
            - name: TZ
              value: UTC
          image: postgres:16.2-alpine
          name: exminds-core-postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
              subPath: postgres
      restartPolicy: Always
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
