apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.backend.ingressName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.global.backend.serviceName }}
            port:
              number: {{ .Values.global.backend.ingressPort }}
