apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.backend.serviceName }}
  labels:
    app: {{ template "backend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.global.backend.serviceType }}
  ports:
    - port: {{ .Values.global.backend.serviceExternalPort }}
      targetPort: {{ .Values.global.backend.serviceInternalPort }}
      protocol: TCP
      name: {{ .Values.global.backend.serviceName }}
  selector:
    app: {{ template "backend.name" . }}
    release: {{ .Release.Name }}