# templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-service
  labels:
    app: {{ .Chart.Name }}-backend
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-backend
  ports:
    - port: 3000
      targetPort: 8888
