apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.locust.loadtest.locust_locustfile_configmap }}
data:
{{- range $path, $bytes := .Files.Glob "files/locust/*" }}
  {{ $path | base | quote }}: |-
    {{ $bytes | toString | nindent 4 }}
{{- end }}
