apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-minikube-storage-provisioner"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-minikube-storage-provisioner"
subjects:
- kind: ServiceAccount
  name: storage-provisioner
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}-minikube-storage-provisioner"
  apiGroup: rbac.authorization.k8s.io
