apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgres.name" . }}
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "postgres.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "postgres.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: static-assets
          configMap:
            name: {{ template "postgres.name" . }}
            defaultMode: {{ .Values.defaultMode }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: static-assets
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}