apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.global.postgres.serviceType }}
  ports:
    - port: {{ .Values.global.postgres.serviceExternalPort }}
      targetPort: {{ .Values.global.postgres.serviceInternalPort }}
      protocol: TCP
      name: {{ .Values.global.postgres.serviceName }}
  selector:
    app: {{ template "postgres.name" . }}
    release: {{ .Release.Name }}