# nestjs-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-kubernetes-namespace
  name: nestjs-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: backend-port
  selector:
    app: nestjs

# nestjs-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-kubernetes-namespace
  name: nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: nestjs
          image: lebinh89/nest_boilerplate:latest
          ports:
            - containerPort: 8888
              name: backend-port
          envFrom:
            - secretRef:
                name: nestjs-kubernetes-secret
          env:
            - name: DATABASE_HOST
              value: postgres-service
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USERNAME
              value: test
            - name: DATABASE_PASSWORD
              value: test
            - name: DATABASE_NAME
              value: test_db
            - name: DB_TIMEZONE
              value: UTC
