apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: {{ .Values.serviceName }}-serect
stringData:
  POSTGRES_DB: test_db
  POSTGRES_PASSWORD: test
  POSTGRES_USER: test
  TZ: UTC
type: Opaque