name: CI/CD Pipeline testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and test
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nest_boilerplate:${{ github.sha }} .
          docker run ${{ secrets.DOCKER_USERNAME }}/nest_boilerplate:${{ github.sha }} npm run test

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nest_boilerplate:${{ github.sha }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Ensures that deploys happen only on main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker and Run App
        run: |
          chmod +x ./dev.sh
          ./dev.sh up docker-compose.prod.yml

      - name: Expose with ngrok
        run: |
          ngrok http $(docker port test-server) --region=us --authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
