name: CI/CD Pipeline testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and test
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nest_boilerplate:${{ github.sha }} .

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nest_boilerplate:${{ github.sha }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Create env file
        run: |
          cat << EOF > .env
          APP_PORT=8888
          PORT=8888
          EOF

      - name: Start Docker and Run App
        run: |
          chmod +x ./dev.sh
          ./dev.sh up docker-compose.prod.yml
          sleep 10  # Wait for containers to fully start
          docker ps

      - name: Expose with ngrok
        run: |
          CONTAINER_ID=$(docker ps -qf "name=test-server")
          if [ -z "$CONTAINER_ID" ]; then
            echo "Container not found, exiting..."
            exit 1
          fi
          PORT_MAPPING=$(docker port $CONTAINER_ID)
          echo "Port Mapping: $PORT_MAPPING"
          PORT=$(echo $PORT_MAPPING | awk -F: '{print $NF}')
          echo "Port extracted: $PORT"
          if [ -z "$PORT" ]; then
            echo "Port not found, exiting..."
            exit 1
          fi
          ./ngrok http $PORT --region=us
